spring.application.name=frases
server.port=8084

spring.datasource.url=jdbc:postgresql://us-east-1.60ed9f6d-cc72-443d-b70a-08ca4681b117.aws.yugabyte.cloud:5433/yugabyte
spring.datasource.username=admin
spring.datasource.password=m4BnvhgakJ9fYTnYmLLezT2W28FptY
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
